services:
  envoy:
    image: envoyproxy/envoy:v1.25-latest
    volumes:
    - ./envoy.yaml:/etc/envoy/envoy.yaml
    # environment:
    # - ENVOY_UID=$(id -u)
    ports:
    - 5000:5000
    - 9901:9901
    
    networks:
     app-network:

  process-server:
    image: marcusforte/duna-cloud-processing

    expose:
     - 10001
    networks:
     app-network:

networks:
  app-network: