name: Duna Pointcloud Tools

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build-and-test:
    runs-on: duna-runner

    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: ./docker_build.sh