name: Duna Pointcloud Tools

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build-and-test:
    runs-on:
      group: duna-pool

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Build
        run: ./docker_build.sh

      - name: Test Scan Matching
        run: docker run duna-pointcloud-tools ctest --test-dir /app/build/scan_matching
      
      - name: Test Scan GRPC filter service
        run: docker run duna-pointcloud-tools ctest --test-dir /app/build/grpc