name: Duna Pointcloud Tools

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build-and-test:
    runs-on:
      group: duna-pool

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Build
        run: docker build -f Dockerfile --build-arg BASE=ubuntu:latest -t duna-pointcloud-tools .

      - name: Test Scan Matching
        run: docker run duna-pointcloud-tools ctest --test-dir /app/build/scan_matching
      
      - name: Test GRPC filter service
        run: docker run duna-pointcloud-tools ctest --test-dir /app/build/grpc

      - name: Test Metrics
        run: docker run duna-pointcloud-tools ctest --test-dir /app/build/metrics